onEvent('item.registry', event => {
    event.create('mu_jian', 'sword')
        .displayName("\u00A7c木剑+13")
        .tier('wood')
        .attackDamageBonus(6)
        .maxStackSize(1)
        .speedBaseline(-2)
        .maxDamage(200)
        .rarity(Rarity.UNCOMMON)
        .tooltip('\u00A77隐藏武器（可转生）')
        .tooltip('\u00A78剑意:攻击额外造成生物护甲值50%的伤害')

    event.create('mu_jian_seven', 'sword')
        .displayName("木剑+7")
        .tier('wood')
        .attackDamageBonus(3)
        .maxStackSize(1)
        .speedBaseline(-2)
        .maxDamage(200)
        .rarity(Rarity.COMMON)
        .tooltip('\u00A77隐藏武器')
        .tooltip('\u00A78剑意:攻击额外造成生物护甲值25%的伤害')

    event.create('yuan_mu_jian', 'sword')
        .displayName("\u00A7c原木剑+13")
        .tier('wood')
        .attackDamageBonus(7)
        .maxStackSize(1)
        .speedBaseline(-2)
        .maxDamage(200)
        .rarity(Rarity.UNCOMMON)
        .tooltip('\u00A77隐藏武器（可转生）')
        .tooltip('\u00A78剑意:攻击额外造成生物护甲值200%的伤害')

    event.create('yuan_mu_jian_seven', 'sword')
        .displayName("原木剑+7")
        .tier('wood')
        .attackDamageBonus(4)
        .maxStackSize(1)
        .speedBaseline(-2)
        .maxDamage(200)
        .rarity(Rarity.COMMON)
        .tooltip('\u00A77隐藏武器')
        .tooltip('\u00A78剑意:攻击额外造成生物护甲值100%的伤害')

    event.create('yuan_mu_jian_one', 'sword')
        .displayName("原木剑")
        .tier('wood')
        .attackDamageBonus(1)
        .maxStackSize(1)
        .speedBaseline(-2)
        .maxDamage(100)
        .rarity(Rarity.COMMON)
        .tooltip('\u00A77隐藏武器')
        .tooltip('\u00A78剑意:攻击额外造成生物护甲值50%的伤害')
    
    event.create('shi_lian')
    .displayName("十连抽卡券")
    .tooltip("\u00A7e\u00A7l右键抽一次十连")
    .maxStackSize(10)
    .rarity(Rarity.UNCOMMON)

    event.create('boss_rush')
    .displayName("远古之魂")
    .tooltip("\u00A7e\u00A7l右键召唤所有boss")
    .tooltip("\u00A74后果自负!")
    .maxStackSize(1)
    .rarity(Rarity.UNCOMMON)

    event.create('sheng_jin')
	.displayName("§6神金")
	.tooltip(Text.translate('圣金'))
	.maxStackSize(1)
	.rarity(Rarity.UNCOMMON)
    .tag('kubejs:sheng_jin')
})
