onEvent('item.registry', event => {
    event.create('mu_jian', 'sword')
        .displayName("\u00A7c木剑+13")
        .tier('wood')
        .attackDamageBonus(6)
        .maxStackSize(1)
        .speedBaseline(-2)
        .maxDamage(200)
        .rarity(Rarity.UNCOMMON)
        .tooltip('\u00A77隐藏武器（可转生）')
        .tooltip('\u00A78剑意:攻击额外造成生物护甲值50%的伤害')

    event.create('mu_jian_seven', 'sword')
        .displayName("木剑+7")
        .tier('wood')
        .attackDamageBonus(3)
        .maxStackSize(1)
        .speedBaseline(-2)
        .maxDamage(200)
        .rarity(Rarity.COMMON)
        .tooltip('\u00A77隐藏武器')
        .tooltip('\u00A78剑意:攻击额外造成生物护甲值25%的伤害')

    event.create('yuan_mu_jian', 'sword')
        .displayName("\u00A7c原木剑+13")
        .tier('wood')
        .attackDamageBonus(7)
        .maxStackSize(1)
        .speedBaseline(-2)
        .maxDamage(200)
        .rarity(Rarity.UNCOMMON)
        .tooltip('\u00A77隐藏武器（可转生）')
        .tooltip('\u00A78剑意:攻击额外造成生物护甲值200%的伤害')

    event.create('yuan_mu_jian_seven', 'sword')
        .displayName("原木剑+7")
        .tier('wood')
        .attackDamageBonus(4)
        .maxStackSize(1)
        .speedBaseline(-2)
        .maxDamage(200)
        .rarity(Rarity.COMMON)
        .tooltip('\u00A77隐藏武器')
        .tooltip('\u00A78剑意:攻击额外造成生物护甲值100%的伤害')

    event.create('yuan_mu_jian_one', 'sword')
        .displayName("原木剑")
        .tier('wood')
        .attackDamageBonus(1)
        .maxStackSize(1)
        .speedBaseline(-2)
        .maxDamage(100)
        .rarity(Rarity.COMMON)
        .tooltip('\u00A77隐藏武器')
        .tooltip('\u00A78剑意:攻击额外造成生物护甲值50%的伤害')
})