onEvent('recipes', event => {
    Ingredient.of('#c:axes').getItemIds().forEach(element => {
        event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:13f,freezeDur:13f,slowDur:13f}}}'), 'kubejs:upgrade_frost', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{POISON:{bonusDmg:14f,dur:14f}}}'), 'kubejs:upgrade_poison', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_fire', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f}}}'), 'kubejs:upgrade_crit', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{LIFESTEAL:{lifesteal:25f}}}'), 'kubejs:upgrade_lifesteal', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:15f,freezeDur:15f,slowDur:15f},POISON:{bonusDmg:15f,dur:15f},FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_yuan', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f},LIFESTEAL:{lifesteal:30f}}}'), 'kubejs:upgrade_ren', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:20f,freezeDur:20f,slowDur:20f},POISON:{bonusDmg:20f,dur:20f},FIRE:{bonusDmg:20f,dur:20f},CRIT:{critChance:2f},LIFESTEAL:{lifesteal:50f}}}'), 'kubejs:upgrade_liuren', Item.of(element).ignoreNBT())
    });
    Ingredient.of('#c:swords').getItemIds().forEach(element => {
        event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:13f,freezeDur:13f,slowDur:13f}}}'), 'kubejs:upgrade_frost', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{POISON:{bonusDmg:14f,dur:14f}}}'), 'kubejs:upgrade_poison', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_fire', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f}}}'), 'kubejs:upgrade_crit', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{LIFESTEAL:{lifesteal:25f}}}'), 'kubejs:upgrade_lifesteal', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:15f,freezeDur:15f,slowDur:15f},POISON:{bonusDmg:15f,dur:15f},FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_yuan', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f},LIFESTEAL:{lifesteal:30f}}}'), 'kubejs:upgrade_ren', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:20f,freezeDur:20f,slowDur:20f},POISON:{bonusDmg:20f,dur:20f},FIRE:{bonusDmg:20f,dur:20f},CRIT:{critChance:2f},LIFESTEAL:{lifesteal:50f}}}'), 'kubejs:upgrade_liuren', Item.of(element).ignoreNBT())
    });
    Ingredient.of('#tier:1weapon').getItemIds().forEach(element => {
        event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:13f,freezeDur:13f,slowDur:13f}}}'), 'kubejs:upgrade_frost', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{POISON:{bonusDmg:14f,dur:14f}}}'), 'kubejs:upgrade_poison', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_fire', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f}}}'), 'kubejs:upgrade_crit', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{LIFESTEAL:{lifesteal:25f}}}'), 'kubejs:upgrade_lifesteal', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:15f,freezeDur:15f,slowDur:15f},POISON:{bonusDmg:15f,dur:15f},FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_yuan', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f},LIFESTEAL:{lifesteal:30f}}}'), 'kubejs:upgrade_ren', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:20f,freezeDur:20f,slowDur:20f},POISON:{bonusDmg:20f,dur:20f},FIRE:{bonusDmg:20f,dur:20f},CRIT:{critChance:2f},LIFESTEAL:{lifesteal:50f}}}'), 'kubejs:upgrade_liuren', Item.of(element).ignoreNBT())
    });
    Ingredient.of('#tier:2weapon').getItemIds().forEach(element => {
        event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:13f,freezeDur:13f,slowDur:13f}}}'), 'kubejs:upgrade_frost', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{POISON:{bonusDmg:14f,dur:14f}}}'), 'kubejs:upgrade_poison', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_fire', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f}}}'), 'kubejs:upgrade_crit', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{LIFESTEAL:{lifesteal:25f}}}'), 'kubejs:upgrade_lifesteal', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:15f,freezeDur:15f,slowDur:15f},POISON:{bonusDmg:15f,dur:15f},FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_yuan', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f},LIFESTEAL:{lifesteal:30f}}}'), 'kubejs:upgrade_ren', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:20f,freezeDur:20f,slowDur:20f},POISON:{bonusDmg:20f,dur:20f},FIRE:{bonusDmg:20f,dur:20f},CRIT:{critChance:2f},LIFESTEAL:{lifesteal:50f}}}'), 'kubejs:upgrade_liuren', Item.of(element).ignoreNBT())
    });
    Ingredient.of('#tier:3weapon').getItemIds().forEach(element => {
        event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:13f,freezeDur:13f,slowDur:13f}}}'), 'kubejs:upgrade_frost', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{POISON:{bonusDmg:14f,dur:14f}}}'), 'kubejs:upgrade_poison', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_fire', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f}}}'), 'kubejs:upgrade_crit', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{LIFESTEAL:{lifesteal:25f}}}'), 'kubejs:upgrade_lifesteal', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:15f,freezeDur:15f,slowDur:15f},POISON:{bonusDmg:15f,dur:15f},FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_yuan', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f},LIFESTEAL:{lifesteal:30f}}}'), 'kubejs:upgrade_ren', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:20f,freezeDur:20f,slowDur:20f},POISON:{bonusDmg:20f,dur:20f},FIRE:{bonusDmg:20f,dur:20f},CRIT:{critChance:2f},LIFESTEAL:{lifesteal:50f}}}'), 'kubejs:upgrade_liuren', Item.of(element).ignoreNBT())
    });
    Ingredient.of('#tier:4weapon').getItemIds().forEach(element => {
        event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:13f,freezeDur:13f,slowDur:13f}}}'), 'kubejs:upgrade_frost', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{POISON:{bonusDmg:14f,dur:14f}}}'), 'kubejs:upgrade_poison', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_fire', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f}}}'), 'kubejs:upgrade_crit', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{LIFESTEAL:{lifesteal:25f}}}'), 'kubejs:upgrade_lifesteal', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:15f,freezeDur:15f,slowDur:15f},POISON:{bonusDmg:15f,dur:15f},FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_yuan', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f},LIFESTEAL:{lifesteal:30f}}}'), 'kubejs:upgrade_ren', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:20f,freezeDur:20f,slowDur:20f},POISON:{bonusDmg:20f,dur:20f},FIRE:{bonusDmg:20f,dur:20f},CRIT:{critChance:2f},LIFESTEAL:{lifesteal:50f}}}'), 'kubejs:upgrade_liuren', Item.of(element).ignoreNBT())
    });
    Ingredient.of('#tier:5weapon').getItemIds().forEach(element => {
        event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:13f,freezeDur:13f,slowDur:13f}}}'), 'kubejs:upgrade_frost', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{POISON:{bonusDmg:14f,dur:14f}}}'), 'kubejs:upgrade_poison', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_fire', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f}}}'), 'kubejs:upgrade_crit', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{LIFESTEAL:{lifesteal:25f}}}'), 'kubejs:upgrade_lifesteal', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:15f,freezeDur:15f,slowDur:15f},POISON:{bonusDmg:15f,dur:15f},FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_yuan', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{CRIT:{critChance:1f},LIFESTEAL:{lifesteal:30f}}}'), 'kubejs:upgrade_ren', Item.of(element).ignoreNBT())
		event.smithing(Item.of(element).withNBT('{Tiered:{Tier:"tiered:legendary"},swa3:{COLD:{bonusDmg:20f,freezeDur:20f,slowDur:20f},POISON:{bonusDmg:20f,dur:20f},FIRE:{bonusDmg:20f,dur:20f},CRIT:{critChance:2f},LIFESTEAL:{lifesteal:50f}}}'), 'kubejs:upgrade_liuren', Item.of(element).ignoreNBT())
    });
	Ingredient.of('#kubejs:mu_jian').getItemIds().forEach(item => {
		event.smithing(Item.of(item).withNBT('{swa3:{COLD:{bonusDmg:13f,freezeDur:13f,slowDur:13f}}}'), 'kubejs:upgrade_frost', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{POISON:{bonusDmg:14f,dur:14f}}}'), 'kubejs:upgrade_poison', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_fire', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{CRIT:{critChance:1f}}}'), 'kubejs:upgrade_crit', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{LIFESTEAL:{lifesteal:25f}}}'), 'kubejs:upgrade_lifesteal', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{COLD:{bonusDmg:15f,freezeDur:15f,slowDur:15f},POISON:{bonusDmg:15f,dur:15f},FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_yuan', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{CRIT:{critChance:1f},LIFESTEAL:{lifesteal:30f}}}'), 'kubejs:upgrade_ren', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{COLD:{bonusDmg:20f,freezeDur:20f,slowDur:20f},POISON:{bonusDmg:20f,dur:20f},FIRE:{bonusDmg:20f,dur:20f},CRIT:{critChance:2f},LIFESTEAL:{lifesteal:50f}}}'), 'kubejs:upgrade_liuren', Item.of(item).ignoreNBT())
	});
	Ingredient.of('#kubejs:s_weapon').getItemIds().forEach(item => {
		event.smithing(Item.of(item).withNBT('{swa3:{COLD:{bonusDmg:13f,freezeDur:13f,slowDur:13f}}}'), 'kubejs:upgrade_frost', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{POISON:{bonusDmg:14f,dur:14f}}}'), 'kubejs:upgrade_poison', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_fire', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{CRIT:{critChance:1f}}}'), 'kubejs:upgrade_crit', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{LIFESTEAL:{lifesteal:25f}}}'), 'kubejs:upgrade_lifesteal', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{COLD:{bonusDmg:15f,freezeDur:15f,slowDur:15f},POISON:{bonusDmg:15f,dur:15f},FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:upgrade_yuan', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{CRIT:{critChance:1f},LIFESTEAL:{lifesteal:30f}}}'), 'kubejs:upgrade_ren', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item).withNBT('{swa3:{COLD:{bonusDmg:20f,freezeDur:20f,slowDur:20f},POISON:{bonusDmg:20f,dur:20f},FIRE:{bonusDmg:20f,dur:20f},CRIT:{critChance:2f},LIFESTEAL:{lifesteal:50f}}}'), 'kubejs:upgrade_liuren', Item.of(item).ignoreNBT())
	});

Ingredient.of('#kubejs:primordial').getItemIds().forEach(item => {
		event.smithing(Item.of(item + '_upgrade_frost'), 'kubejs:upgrade_frost', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item + '_upgrade_poison'), 'kubejs:upgrade_poison', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item + '_upgrade_fire'), 'kubejs:upgrade_fire', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item + '_upgrade_crit'), 'kubejs:upgrade_crit', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item + '_upgrade_lifesteal'), 'kubejs:upgrade_lifesteal', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item + '_upgrade_yuan'), 'kubejs:upgrade_yuan', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item + '_upgrade_ren'), 'kubejs:upgrade_ren', Item.of(item).ignoreNBT())
		event.smithing(Item.of(item + '_upgrade'), 'kubejs:upgrade_liuren', Item.of(item).ignoreNBT())
	});

		event.smithing(Item.of('kubejs:qixing_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"}}'), 'kubejs:primordial_qixing', Item.of('kubejs:qixing_sword').ignoreNBT())
        event.smithing(Item.of('kubejs:qixing_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{COLD:{bonusDmg:13f,freezeDur:13f,slowDur:13f}}}'), 'kubejs:primordial_qixing_upgrade_frost', Item.of('kubejs:qixing_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:qixing_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{POISON:{bonusDmg:14f,dur:14f}}}'), 'kubejs:primordial_qixing_upgrade_poison', Item.of('kubejs:qixing_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:qixing_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:primordial_qixing_upgrade_fire', Item.of('kubejs:qixing_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:qixing_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{CRIT:{critChance:1f}}}'), 'kubejs:primordial_qixing_upgrade_crit', Item.of('kubejs:qixing_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:qixing_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{LIFESTEAL:{lifesteal:25f}}}'), 'kubejs:primordial_qixing_upgrade_lifesteal', Item.of('kubejs:qixing_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:qixing_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{COLD:{bonusDmg:15f,freezeDur:15f,slowDur:15f},POISON:{bonusDmg:15f,dur:15f},FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:primordial_qixing_upgrade_yuan', Item.of('kubejs:qixing_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:qixing_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{CRIT:{critChance:1f},LIFESTEAL:{lifesteal:30f}}}'), 'kubejs:primordial_qixing_upgrade_ren', Item.of('kubejs:qixing_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:qixing_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{COLD:{bonusDmg:20f,freezeDur:20f,slowDur:20f},POISON:{bonusDmg:20f,dur:20f},FIRE:{bonusDmg:20f,dur:20f},CRIT:{critChance:2f},LIFESTEAL:{lifesteal:50f}}}'), 'kubejs:primordial_qixing_upgrade', Item.of('kubejs:qixing_sword').ignoreNBT())

		event.smithing(Item.of('kubejs:ruoshui_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"}}'), 'kubejs:primordial_ruoshui', Item.of('kubejs:ruoshui_sword').ignoreNBT())
        event.smithing(Item.of('kubejs:ruoshui_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{COLD:{bonusDmg:13f,freezeDur:13f,slowDur:13f}}}'), 'kubejs:primordial_ruoshui_upgrade_frost', Item.of('kubejs:ruoshui_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:ruoshui_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{POISON:{bonusDmg:14f,dur:14f}}}'), 'kubejs:primordial_ruoshui_upgrade_poison', Item.of('kubejs:ruoshui_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:ruoshui_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:primordial_ruoshui_upgrade_fire', Item.of('kubejs:ruoshui_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:ruoshui_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{CRIT:{critChance:1f}}}'), 'kubejs:primordial_ruoshui_upgrade_crit', Item.of('kubejs:ruoshui_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:ruoshui_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{LIFESTEAL:{lifesteal:25f}}}'), 'kubejs:primordial_ruoshui_upgrade_lifesteal', Item.of('kubejs:ruoshui_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:ruoshui_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{COLD:{bonusDmg:15f,freezeDur:15f,slowDur:15f},POISON:{bonusDmg:15f,dur:15f},FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:primordial_ruoshui_upgrade_yuan', Item.of('kubejs:ruoshui_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:ruoshui_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{CRIT:{critChance:1f},LIFESTEAL:{lifesteal:30f}}}'), 'kubejs:primordial_ruoshui_upgrade_ren', Item.of('kubejs:ruoshui_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:ruoshui_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{COLD:{bonusDmg:20f,freezeDur:20f,slowDur:20f},POISON:{bonusDmg:20f,dur:20f},FIRE:{bonusDmg:20f,dur:20f},CRIT:{critChance:2f},LIFESTEAL:{lifesteal:50f}}}'), 'kubejs:primordial_ruoshui_upgrade', Item.of('kubejs:ruoshui_sword').ignoreNBT())

		event.smithing(Item.of('kubejs:putong_stone_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"}}'), 'kubejs:primordial_stone', Item.of('kubejs:putong_stone_sword').ignoreNBT())
        event.smithing(Item.of('kubejs:putong_stone_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{COLD:{bonusDmg:13f,freezeDur:13f,slowDur:13f}}}'), 'kubejs:primordial_stone_upgrade_frost', Item.of('kubejs:putong_stone_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:putong_stone_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{POISON:{bonusDmg:14f,dur:14f}}}'), 'kubejs:primordial_stone_upgrade_poison', Item.of('kubejs:putong_stone_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:putong_stone_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:primordial_stone_upgrade_fire', Item.of('kubejs:putong_stone_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:putong_stone_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{CRIT:{critChance:1f}}}'), 'kubejs:primordial_stone_upgrade_crit', Item.of('kubejs:putong_stone_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:putong_stone_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{LIFESTEAL:{lifesteal:25f}}}'), 'kubejs:primordial_stone_upgrade_lifesteal', Item.of('kubejs:putong_stone_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:putong_stone_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{COLD:{bonusDmg:15f,freezeDur:15f,slowDur:15f},POISON:{bonusDmg:15f,dur:15f},FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:primordial_stone_upgrade_yuan', Item.of('kubejs:putong_stone_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:putong_stone_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{CRIT:{critChance:1f},LIFESTEAL:{lifesteal:30f}}}'), 'kubejs:primordial_stone_upgrade_ren', Item.of('kubejs:putong_stone_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:putong_stone_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{COLD:{bonusDmg:20f,freezeDur:20f,slowDur:20f},POISON:{bonusDmg:20f,dur:20f},FIRE:{bonusDmg:20f,dur:20f},CRIT:{critChance:2f},LIFESTEAL:{lifesteal:50f}}}'), 'kubejs:primordial_stone_upgrade', Item.of('kubejs:putong_stone_sword').ignoreNBT())

		event.smithing(Item.of('kubejs:yecao_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"}}'), 'kubejs:primordial_yecao', Item.of('kubejs:yecao_sword').ignoreNBT())
        event.smithing(Item.of('kubejs:yecao_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{COLD:{bonusDmg:13f,freezeDur:13f,slowDur:13f}}}'), 'kubejs:primordial_yecao_upgrade_frost', Item.of('kubejs:yecao_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:yecao_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{POISON:{bonusDmg:14f,dur:14f}}}'), 'kubejs:primordial_yecao_upgrade_poison', Item.of('kubejs:yecao_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:yecao_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:primordial_yecao_upgrade_fire', Item.of('kubejs:yecao_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:yecao_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{CRIT:{critChance:1f}}}'), 'kubejs:primordial_yecao_upgrade_crit', Item.of('kubejs:yecao_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:yecao_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{LIFESTEAL:{lifesteal:25f}}}'), 'kubejs:primordial_yecao_upgrade_lifesteal', Item.of('kubejs:yecao_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:yecao_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{COLD:{bonusDmg:15f,freezeDur:15f,slowDur:15f},POISON:{bonusDmg:15f,dur:15f},FIRE:{bonusDmg:15f,dur:15f}}}'), 'kubejs:primordial_yecao_upgrade_yuan', Item.of('kubejs:yecao_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:yecao_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{CRIT:{critChance:1f},LIFESTEAL:{lifesteal:30f}}}'), 'kubejs:primordial_yecao_upgrade_ren', Item.of('kubejs:yecao_sword').ignoreNBT())
		event.smithing(Item.of('kubejs:yecao_sword').withNBT('{Tiered:{Tier:"tiered:qixing_melee2"},swa3:{COLD:{bonusDmg:20f,freezeDur:20f,slowDur:20f},POISON:{bonusDmg:20f,dur:20f},FIRE:{bonusDmg:20f,dur:20f},CRIT:{critChance:2f},LIFESTEAL:{lifesteal:50f}}}'), 'kubejs:primordial_yecao_upgrade', Item.of('kubejs:yecao_sword').ignoreNBT())
})