onEvent('recipes', event => {
	event.smithing(Item.of('test_helmet').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('test_helmet').ignoreNBT())
	event.smithing(Item.of('test_helmet').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('test_helmet').ignoreNBT())
	event.smithing(Item.of('test_chestplate').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('test_chestplate').ignoreNBT())
	event.smithing(Item.of('test_chestplate').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('test_chestplate').ignoreNBT())
	event.smithing(Item.of('test_leggings').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('test_leggings').ignoreNBT())
	event.smithing(Item.of('test_leggings').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('test_leggings').ignoreNBT())
	event.smithing(Item.of('test_boots').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('test_boots').ignoreNBT())
	event.smithing(Item.of('test_boots').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('test_boots').ignoreNBT())


	event.smithing(Item.of('mcda:sturdy_shulker_armor_helmet').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:sturdy_shulker_armor_helmet').ignoreNBT())
	event.smithing(Item.of('mcda:sturdy_shulker_armor_helmet').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('mcda:sturdy_shulker_armor_helmet').ignoreNBT())
	event.smithing(Item.of('mcda:sturdy_shulker_armor_helmet').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('mcda:sturdy_shulker_armor_helmet').ignoreNBT())
	event.smithing(Item.of('mcda:sturdy_shulker_armor_chestplate').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:sturdy_shulker_armor_chestplate').ignoreNBT())
	event.smithing(Item.of('mcda:sturdy_shulker_armor_chestplate').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('mcda:sturdy_shulker_armor_chestplate').ignoreNBT())
	event.smithing(Item.of('mcda:sturdy_shulker_armor_chestplate').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('mcda:sturdy_shulker_armor_chestplate').ignoreNBT())
	event.smithing(Item.of('mcda:sturdy_shulker_armor_leggings').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:sturdy_shulker_armor_leggings').ignoreNBT())
	event.smithing(Item.of('mcda:sturdy_shulker_armor_leggings').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('mcda:sturdy_shulker_armor_leggings').ignoreNBT())
	event.smithing(Item.of('mcda:sturdy_shulker_armor_leggings').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('mcda:sturdy_shulker_armor_leggings').ignoreNBT())
	event.smithing(Item.of('mcda:sturdy_shulker_armor_boots').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:sturdy_shulker_armor_boots').ignoreNBT())
	event.smithing(Item.of('mcda:sturdy_shulker_armor_boots').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('mcda:sturdy_shulker_armor_boots').ignoreNBT())
	event.smithing(Item.of('mcda:sturdy_shulker_armor_boots').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('mcda:sturdy_shulker_armor_boots').ignoreNBT())

	event.smithing(Item.of('gobber2:gobber2_helmet_nether').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('gobber2:gobber2_helmet_nether').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_helmet_nether').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('gobber2:gobber2_helmet_nether').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_helmet_nether').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('gobber2:gobber2_helmet_nether').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_chestplate_nether').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('gobber2:gobber2_chestplate_nether').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_chestplate_nether').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('gobber2:gobber2_chestplate_nether').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_chestplate_nether').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('gobber2:gobber2_chestplate_nether').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_leggings_nether').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('gobber2:gobber2_leggings_nether').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_leggings_nether').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('gobber2:gobber2_leggings_nether').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_leggings_nether').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('gobber2:gobber2_leggings_nether').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_boots_nether').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('gobber2:gobber2_boots_nether').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_boots_nether').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('gobber2:gobber2_boots_nether').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_boots_nether').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('gobber2:gobber2_boots_nether').ignoreNBT())

	event.smithing(Item.of('gobber2:gobber2_helmet_end').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('gobber2:gobber2_helmet_end').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_helmet_end').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('gobber2:gobber2_helmet_end').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_helmet_end').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('gobber2:gobber2_helmet_end').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_chestplate_end').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('gobber2:gobber2_chestplate_end').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_chestplate_end').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('gobber2:gobber2_chestplate_end').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_chestplate_end').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('gobber2:gobber2_chestplate_end').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_leggings_end').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('gobber2:gobber2_leggings_end').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_leggings_end').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('gobber2:gobber2_leggings_end').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_leggings_end').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('gobber2:gobber2_leggings_end').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_boots_end').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('gobber2:gobber2_boots_end').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_boots_end').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('gobber2:gobber2_boots_end').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_boots_end').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('gobber2:gobber2_boots_end').ignoreNBT())

	event.smithing(Item.of('gobber2:gobber2_helmet_dragon').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('gobber2:gobber2_helmet_dragon').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_helmet_dragon').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('gobber2:gobber2_helmet_dragon').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_helmet_dragon').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('gobber2:gobber2_helmet_dragon').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_chestplate_dragon').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('gobber2:gobber2_chestplate_dragon').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_chestplate_dragon').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('gobber2:gobber2_chestplate_dragon').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_chestplate_dragon').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('gobber2:gobber2_chestplate_dragon').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_leggings_dragon').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('gobber2:gobber2_leggings_dragon').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_leggings_dragon').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('gobber2:gobber2_leggings_dragon').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_leggings_dragon').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('gobber2:gobber2_leggings_dragon').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_boots_dragon').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('gobber2:gobber2_boots_dragon').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_boots_dragon').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('gobber2:gobber2_boots_dragon').ignoreNBT())
	event.smithing(Item.of('gobber2:gobber2_boots_dragon').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('gobber2:gobber2_boots_dragon').ignoreNBT())

	event.smithing(Item.of('spectrum:bedrock_helmet').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('spectrum:bedrock_helmet').ignoreNBT())
	event.smithing(Item.of('spectrum:bedrock_helmet').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('spectrum:bedrock_helmet').ignoreNBT())
	event.smithing(Item.of('spectrum:bedrock_helmet').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('spectrum:bedrock_helmet').ignoreNBT())
	event.smithing(Item.of('spectrum:bedrock_chestplate').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('spectrum:bedrock_chestplate').ignoreNBT())
	event.smithing(Item.of('spectrum:bedrock_chestplate').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('spectrum:bedrock_chestplate').ignoreNBT())
	event.smithing(Item.of('spectrum:bedrock_chestplate').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('spectrum:bedrock_chestplate').ignoreNBT())
	event.smithing(Item.of('spectrum:bedrock_leggings').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('spectrum:bedrock_leggings').ignoreNBT())
	event.smithing(Item.of('spectrum:bedrock_leggings').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('spectrum:bedrock_leggings').ignoreNBT())
	event.smithing(Item.of('spectrum:bedrock_leggings').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('spectrum:bedrock_leggings').ignoreNBT())
	event.smithing(Item.of('spectrum:bedrock_boots').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('spectrum:bedrock_boots').ignoreNBT())
	event.smithing(Item.of('spectrum:bedrock_boots').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('spectrum:bedrock_boots').ignoreNBT())
	event.smithing(Item.of('spectrum:bedrock_boots').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('spectrum:bedrock_boots').ignoreNBT())

	event.smithing(Item.of('dragonloot:dragon_helmet').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('dragonloot:dragon_helmet').ignoreNBT())
	event.smithing(Item.of('dragonloot:dragon_helmet').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('dragonloot:dragon_helmet').ignoreNBT())
	event.smithing(Item.of('dragonloot:dragon_helmet').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('dragonloot:dragon_helmet').ignoreNBT())
	event.smithing(Item.of('dragonloot:dragon_chestplate').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('dragonloot:dragon_chestplate').ignoreNBT())
	event.smithing(Item.of('dragonloot:dragon_chestplate').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('dragonloot:dragon_chestplate').ignoreNBT())
	event.smithing(Item.of('dragonloot:dragon_chestplate').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('dragonloot:dragon_chestplate').ignoreNBT())
	event.smithing(Item.of('dragonloot:dragon_leggings').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('dragonloot:dragon_leggings').ignoreNBT())
	event.smithing(Item.of('dragonloot:dragon_leggings').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('dragonloot:dragon_leggings').ignoreNBT())
	event.smithing(Item.of('dragonloot:dragon_leggings').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('dragonloot:dragon_leggings').ignoreNBT())
	event.smithing(Item.of('dragonloot:dragon_boots').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('dragonloot:dragon_boots').ignoreNBT())
	event.smithing(Item.of('dragonloot:dragon_boots').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('dragonloot:dragon_boots').ignoreNBT())
	event.smithing(Item.of('dragonloot:dragon_boots').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('dragonloot:dragon_boots').ignoreNBT())
	event.smithing(Item.of('dragonloot:upgraded_dragon_chestplate').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('dragonloot:upgraded_dragon_chestplate').ignoreNBT())
	event.smithing(Item.of('dragonloot:upgraded_dragon_chestplate').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:15f}}}'), 'kubejs:upgrade_defence', Item.of('dragonloot:upgraded_dragon_chestplate').ignoreNBT())
	event.smithing(Item.of('dragonloot:upgraded_dragon_chestplate').withNBT('{saa1:{DMG_REDUCTION:{dmgReduc:20f},MAX_HEALTH:{bonusMaxHP:20f}}}'), 'kubejs:upgrade_nami', Item.of('dragonloot:upgraded_dragon_chestplate').ignoreNBT())

	event.smithing(Item.of('mcda:blue_mystery_armor_helmet').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:blue_mystery_armor_helmet').ignoreNBT())
	event.smithing(Item.of('mcda:blue_mystery_armor_chestplate').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:blue_mystery_armor_chestplate').ignoreNBT())
	event.smithing(Item.of('mcda:blue_mystery_armor_leggings').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:blue_mystery_armor_leggings').ignoreNBT())
	event.smithing(Item.of('mcda:blue_mystery_armor_boots').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:blue_mystery_armor_boots').ignoreNBT())

	event.smithing(Item.of('mcda:white_mystery_armor_helmet').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:white_mystery_armor_helmet').ignoreNBT())
	event.smithing(Item.of('mcda:white_mystery_armor_chestplate').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:white_mystery_armor_chestplate').ignoreNBT())
	event.smithing(Item.of('mcda:white_mystery_armor_leggings').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:white_mystery_armor_leggings').ignoreNBT())
	event.smithing(Item.of('mcda:white_mystery_armor_boots').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:white_mystery_armor_boots').ignoreNBT())

	event.smithing(Item.of('mcda:purple_mystery_armor_helmet').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:purple_mystery_armor_helmet').ignoreNBT())
	event.smithing(Item.of('mcda:purple_mystery_armor_chestplate').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:purple_mystery_armor_chestplate').ignoreNBT())
	event.smithing(Item.of('mcda:purple_mystery_armor_leggings').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:purple_mystery_armor_leggings').ignoreNBT())
	event.smithing(Item.of('mcda:purple_mystery_armor_boots').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:purple_mystery_armor_boots').ignoreNBT())

	event.smithing(Item.of('mcda:red_mystery_armor_helmet').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:red_mystery_armor_helmet').ignoreNBT())
	event.smithing(Item.of('mcda:red_mystery_armor_chestplate').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:red_mystery_armor_chestplate').ignoreNBT())
	event.smithing(Item.of('mcda:red_mystery_armor_leggings').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:red_mystery_armor_leggings').ignoreNBT())
	event.smithing(Item.of('mcda:red_mystery_armor_boots').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:red_mystery_armor_boots').ignoreNBT())

	event.smithing(Item.of('mcda:green_mystery_armor_helmet').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:green_mystery_armor_helmet').ignoreNBT())
	event.smithing(Item.of('mcda:green_mystery_armor_chestplate').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:green_mystery_armor_chestplate').ignoreNBT())
	event.smithing(Item.of('mcda:green_mystery_armor_leggings').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:green_mystery_armor_leggings').ignoreNBT())
	event.smithing(Item.of('mcda:green_mystery_armor_boots').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:green_mystery_armor_boots').ignoreNBT())

	event.smithing(Item.of('mcda:gourdian_armor_helmet').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:gourdian_armor_helmet').ignoreNBT())
	event.smithing(Item.of('mcda:gourdian_armor_chestplate').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:gourdian_armor_chestplate').ignoreNBT())
	event.smithing(Item.of('mcda:gourdian_armor_leggings').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:gourdian_armor_leggings').ignoreNBT())
	event.smithing(Item.of('mcda:gourdian_armor_boots').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mcda:gourdian_armor_boots').ignoreNBT())

	event.smithing(Item.of('mythicmetals:metallurgium_helmet').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mythicmetals:metallurgium_helmet').ignoreNBT())
	event.smithing(Item.of('mythicmetals:metallurgium_chestplate').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mythicmetals:metallurgium_chestplate').ignoreNBT())
	event.smithing(Item.of('mythicmetals:metallurgium_leggings').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mythicmetals:metallurgium_leggings').ignoreNBT())
	event.smithing(Item.of('mythicmetals:metallurgium_boots').withNBT('{saa1:{MAX_HEALTH:{bonusMaxHP:10f}}}'), 'kubejs:upgrade_life', Item.of('mythicmetals:metallurgium_boots').ignoreNBT())


})