ENABLE_OVERLAY = true
OVERLAY_LAYOUT_STYLE = 1
ENABLE_HEALTH_BLINK = true
LOW_HEALTH_RATE = 0.2
OVERWRITE_VANILLA_ARMOR_BAR = true
OVERWRITE_VANILLA_EXPERIENCE_BAR = false
DISPLAY_EXPERIENCE_PROGRESS = false
ENABLE_FOOD_BLINK = true
DISPLAY_SATURATION = true
DISPLAY_EXHAUSTION = true
CORNER_BAR_LENGTH = 120
CORNER_HORIZONTAL_PADDING = 16
CORNER_VERTICAL_PADDING = 16
ENABLE_HEALTH_BAR = true
MAX_DISTANCE = 32.0
SHOW_ON_PLAYERS = false
SHOW_ON_BOSSES = true
SHOW_ON_FULL_HEALTH_WITHOUT_ABSORPTION = true
SHOW_ON_FULL_HEALTH_WITH_ABSORPTION = true
HEALTH_BAR_HALF_WIDTH = 50
HEALTH_BAR_HALF_HEIGHT = 3
HEALTH_BAR_OFFSET_Y = 0.2
HEALTH_BAR_SCALE = 0.015
HEALTH_BAR_TEXT_SCALE = 0.8
HEALTH_BAR_TEXT_OFFSET_Y = -2.75
HEALTH_BAR_BOUND_WIDTH = 2
HEALTH_BAR_BOUND_VERTEX = false
HEALTH_BAR_HEALTH_COLOR = -1442807808
HEALTH_BAR_ABSORPTION_COLOR = -1426063616
HEALTH_BAR_BOUND_COLOR = 1426063360
HEALTH_BAR_EMPTY_COLOR = 855638016
HEALTH_BAR_HEALTH_COLOR_DYNAMIC = true
HEALTH_BAR_HEALTH_COLOR_FULL = -1442807808
HEALTH_BAR_HEALTH_COLOR_EMPTY = -1434451968
