
#General mod settings
[general]
	#Delay in ticks between allowed mob wander pathfinds
	#Range: > 0
	mobWanderingDelay = 100
	#Percent chance to run for task: zombie village raid task
	#Range: > 0
	zombieVillageRaidPercentChance = 0
	#If not near a player, the delay in ticks between wander pathfinds are multiplied by this amount
	#Range: > 0
	mobWanderingReducedRateMultiplier = 6
	#If a mob is at least this far away from a player, additional reduced rates are used for the tasks mentioned in playerProximityReducedRate in features.toml
	#Range: > 0
	playerProximityReducedRateRangeCutoff = 12
	#Percent chance to run for task: zombie seeking turtle eggs to destroy
	#Range: > 0
	zombieSearchAndDestroyTurtleEggPercentChance = 0
	#If not near a player, we only allow give the mob this much of a percent chance to search for a target
	#Range: > 0
	mobEnemyTargetingReducedRatePercentChance = 10
	#How often in ticks we update our check on how close a mob is to a player
	#Range: > 0
	playerProximityReducedRatePlayerScanRate = 40
	#In addition to the timed delay, an additional percent chance to run for task: mob wander pathfinding
	#Range: > 0
	mobWanderingPercentChance = 100

