onEvent('item.registry', event => {
	event.create('baigei_boots', 'boots')
		.tier('gold')
		.maxDamage(400)
		.rarity(Rarity.UNCOMMON)
		.tooltip(Text.translate('item.kubejs.baigei_boots.tooltip'))
		.tooltip(Text.translate('item.kubejs.baigei_boots.tooltip1'))
		.tooltip(Text.translate('item.kubejs.baigei_boots.tooltip2'))
		.tooltip(Text.translate('item.kubejs.baigei_boots.tooltip4'))
		.tooltip('')
		.tooltip(Text.translate('item.kubejs.baigei_boots.tooltip3'))

	event.create('huan_lin_ying', 'helmet')
		.displayName("18星海龟壳")
		.tier('turtle')
		.maxDamage(2333)
		.rarity(Rarity.UNCOMMON)
		.tooltip(Text.translate('诺华觉得，穿上这个帽子的人，跟大聪明没区别'))
		.tooltip(Text.translate('无限重生三群管理员:宫上诺华留'))
		.tooltip(Text.translate('--来自赞助者宫上诺华'))
})