onEvent('item.registry', event => {
	event.create('crude_pickaxe', 'pickaxe').tier('stone')
	event.create('crude_axe', 'axe').tier('stone')
	event.create('crude_spade', 'shovel').tier('stone')
	//燧石工具
	event.create('kreska', 'pickaxe')
		.displayName("§f直镐")
		.tier('kreska')
		.rarity(Rarity.EPIC)
		.tooltip('\u00A76\u00A7l✦✦✦✦·圣物')
		.tooltip('\u00A7f压迫点 Prime：+165%近战攻击伤害')
		.tooltip('\u00A7f剑风 Prime：+3攻击范围')
		.tooltip('\u00A72热病打击 Prime：+165%毒素伤害')
		.tooltip('\u00A7c熔岩冲击：+90%火焰伤害')
		.tooltip('\u00A7b北风：+90%冰冻伤害')
		.tooltip('\u00A7a治愈归复：攻击时有概率回血')
		.tooltip('')
		.tooltip('\u00A7f你给路达哟：右键传送到10米外并给予速度效果 冷却5秒')
		.tooltip('\u00A7f忘关就是开？：赋予透视生物效果')
		.tooltip('\u00A7e点石成“金”：挖掘矿物有概率掉落神话矿粒')
		.tooltip('')

	event.create('nature_spirit', 'pickaxe')
		.displayName("§a自然之灵")
		.tier('nature')
		.rarity(Rarity.UNCOMMON)
		.tooltip('\u00A7e\u00A7l✦✦✦✦✦·神器（可转生）')
		.tooltip('\u00A7d寄生之种：击中后对敌方造成持续伤害，持续3秒')
		.tooltip('\u00A73藤蔓缠绕：击中后敌方被藤蔓缠绕无法移动，持续2秒')
		.tooltip('\u00A76元素庇护：挖掘方块时回复少量饱和度和生命值')
		.tooltip('\u00A7b丛林祝福：手持时获得夜视和急迫效果')
		.tooltip('\u00A7c精灵之力：加持元素精灵的祝福，获得额外攻击加成')
		.tooltip('\u00A7a自然恩赐：采集任何矿物时有概率额外获得难得素，与精准采集不兼容')
		.tooltip('')
		.tooltip('\u00A77游玩周目最多玩家@Shu_Zhix')
})